Preparing the Evaluation Dataset and setting the baseline:

In [14]:
%pip install unsloth

Collecting unsloth
  Downloading unsloth-2026.3.4-py3-none-any.whl.metadata (70 kB)
Collecting unsloth_zoo>=2026.3.2 (from unsloth)
  Downloading unsloth_zoo-2026.3.2-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: wheel>=0.42.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from unsloth) (0.46.3)
Requirement already satisfied: packaging in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from unsloth) (25.0)
Requirement already satisfied: torch>=2.4.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from unsloth) (2.10.0)
Collecting torchvision (from unsloth)
  Downloading torchvision-0.25.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (5.4 kB)
Requirement already satisfied: numpy in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from unsloth) (2.4.2)
Requirement already satisfied: tqdm in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from unsloth) (4.67.3)
Requirement already satisfied: psutil in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from unsloth) (7.2.2)
Collecting tyro (from unsloth)
  Downloading tyro-1.0.8-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: protobuf in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from unsloth) (6.33.5)
Collecting xformers>=0.0.27.post2 (from unsloth)
  Downloading xformers-0.0.35-py39-none-manylinux_2_28_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from unsloth) (0.49.2)
Requirement already satisfied: triton>=3.0.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from unsloth) (3.6.0)
Collecting sentencepiece>=0.2.0 (from unsloth)
  Downloading sentencepiece-0.2.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Collecting datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1 (from unsloth)
  Downloading datasets-4.3.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: accelerate>=0.34.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from unsloth) (1.12.0)
Requirement already satisfied: peft!=0.11.0,>=0.18.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from unsloth) (0.18.1)
Requirement already satisfied: huggingface_hub>=0.34.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from unsloth) (0.36.2)
Collecting hf_transfer (from unsloth)
  Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.7 kB)
Collecting diffusers (from unsloth)
  Downloading diffusers-0.37.0-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.2.0,>=4.51.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from unsloth) (5.2.0)
Collecting trl!=0.19.0,<=0.24.0,>=0.18.2 (from unsloth)
  Downloading trl-0.24.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: filelock in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.24.3)
Requirement already satisfied: pyarrow>=21.0.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (23.0.1)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.3.8)
Requirement already satisfied: pandas in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.0.1)
Requirement already satisfied: requests>=2.32.2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.32.5)
Requirement already satisfied: httpx<1.0.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.28.1)
Requirement already satisfied: xxhash in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.70.16)
Requirement already satisfied: fsspec<=2025.9.0,>=2023.1.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2024.9.0)
Requirement already satisfied: pyyaml>=5.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.13.3)
Requirement already satisfied: anyio in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (4.12.1)
Requirement already satisfied: certifi in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.0.9)
Requirement already satisfied: idna in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.11)
Requirement already satisfied: h11>=0.16 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from httpcore==1.*->httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from huggingface_hub>=0.34.0->unsloth) (1.2.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from huggingface_hub>=0.34.0->unsloth) (4.15.0)
Collecting huggingface_hub>=0.34.0 (from unsloth)
  Downloading huggingface_hub-1.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: regex!=2019.12.17 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.2.0,>=4.51.3->unsloth) (2026.2.19)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.2.0,>=4.51.3->unsloth) (0.22.2)
Requirement already satisfied: typer-slim in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.2.0,>=4.51.3->unsloth) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.2.0,>=4.51.3->unsloth) (0.7.0)
Collecting hf-xet<2.0.0,>=1.3.2 (from huggingface_hub>=0.34.0->unsloth)
  Downloading hf_xet-1.3.2-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: typer in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from huggingface_hub>=0.34.0->unsloth) (0.20.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.22.0)
Requirement already satisfied: sympy>=1.13.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from torch>=2.4.0->unsloth) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from torch>=2.4.0->unsloth) (3.6.1)
Requirement already satisfied: jinja2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from torch>=2.4.0->unsloth) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from torch>=2.4.0->unsloth) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from torch>=2.4.0->unsloth) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from torch>=2.4.0->unsloth) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from torch>=2.4.0->unsloth) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from torch>=2.4.0->unsloth) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from torch>=2.4.0->unsloth) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from torch>=2.4.0->unsloth) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from torch>=2.4.0->unsloth) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from torch>=2.4.0->unsloth) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from torch>=2.4.0->unsloth) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from torch>=2.4.0->unsloth) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from torch>=2.4.0->unsloth) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from torch>=2.4.0->unsloth) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from torch>=2.4.0->unsloth) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from torch>=2.4.0->unsloth) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from torch>=2.4.0->unsloth) (1.13.1.3)
Requirement already satisfied: cuda-pathfinder~=1.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from cuda-bindings==12.9.4->torch>=2.4.0->unsloth) (1.3.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.6.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from sympy>=1.13.3->torch>=2.4.0->unsloth) (1.3.0)
Collecting torchao>=0.13.0 (from unsloth_zoo>=2026.3.2->unsloth)
  Downloading torchao-0.16.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (20 kB)
Collecting cut_cross_entropy (from unsloth_zoo>=2026.3.2->unsloth)
  Downloading cut_cross_entropy-25.1.1-py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: pillow in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from unsloth_zoo>=2026.3.2->unsloth) (12.1.1)
Collecting msgspec (from unsloth_zoo>=2026.3.2->unsloth)
  Downloading msgspec-0.20.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting importlib_metadata (from diffusers->unsloth)
  Downloading importlib_metadata-8.7.1-py3-none-any.whl.metadata (4.7 kB)
Collecting zipp>=3.20 (from importlib_metadata->diffusers->unsloth)
  Downloading zipp-3.23.0-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from jinja2->torch>=2.4.0->unsloth) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.17.0)
Requirement already satisfied: click>=8.0.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from typer->huggingface_hub>=0.34.0->unsloth) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from typer->huggingface_hub>=0.34.0->unsloth) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from typer->huggingface_hub>=0.34.0->unsloth) (13.9.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from rich>=10.11.0->typer->huggingface_hub>=0.34.0->unsloth) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from rich>=10.11.0->typer->huggingface_hub>=0.34.0->unsloth) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->huggingface_hub>=0.34.0->unsloth) (0.1.2)
Collecting typer (from huggingface_hub>=0.34.0->unsloth)
  Using cached typer-0.24.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from typer->huggingface_hub>=0.34.0->unsloth) (0.0.4)
Requirement already satisfied: docstring-parser>=0.15 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (from tyro->unsloth) (0.17.0)
Collecting typeguard>=4.0.0 (from tyro->unsloth)
  Downloading typeguard-4.5.1-py3-none-any.whl.metadata (3.8 kB)
Downloading unsloth-2026.3.4-py3-none-any.whl (447 kB)
Downloading datasets-4.3.0-py3-none-any.whl (506 kB)
Downloading huggingface_hub-1.6.0-py3-none-any.whl (612 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 612.9/612.9 kB 34.9 MB/s  0:00:00
Downloading hf_xet-1.3.2-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 174.9 MB/s  0:00:00
Downloading trl-0.24.0-py3-none-any.whl (423 kB)
Downloading sentencepiece-0.2.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 48.8 MB/s  0:00:00
Downloading unsloth_zoo-2026.3.2-py3-none-any.whl (395 kB)
Downloading torchao-0.16.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 116.0 MB/s  0:00:00
Downloading xformers-0.0.35-py39-none-manylinux_2_28_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 146.6 MB/s  0:00:00
Downloading cut_cross_entropy-25.1.1-py3-none-any.whl (22 kB)
Downloading diffusers-0.37.0-py3-none-any.whl (5.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 157.1 MB/s  0:00:00
Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 90.6 MB/s  0:00:00
Downloading importlib_metadata-8.7.1-py3-none-any.whl (27 kB)
Downloading zipp-3.23.0-py3-none-any.whl (10 kB)
Downloading msgspec-0.20.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (219 kB)
Downloading torchvision-0.25.0-cp311-cp311-manylinux_2_28_x86_64.whl (8.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 175.0 MB/s  0:00:00
Using cached typer-0.24.1-py3-none-any.whl (56 kB)
Downloading tyro-1.0.8-py3-none-any.whl (181 kB)
Downloading typeguard-4.5.1-py3-none-any.whl (36 kB)
Installing collected packages: torchao, zipp, typeguard, sentencepiece, msgspec, hf-xet, hf_transfer, tyro, importlib_metadata, typer, xformers, torchvision, huggingface_hub, cut_cross_entropy, diffusers, datasets, trl, unsloth_zoo, unsloth
  Attempting uninstall: hf-xet━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  1/19 [zipp]
    Found existing installation: hf-xet 1.2.0━━━━━━━━━━━━━━━━━  1/19 [zipp]
    Uninstalling hf-xet-1.2.0:0m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/19 [hf-xet]
      Successfully uninstalled hf-xet-1.2.0━━━━━━━━━━━━━━━━━━━  5/19 [hf-xet]
  Attempting uninstall: typer[91m╸━━━━━━━━━━━━━━━━━━━━━━━  8/19 [importlib_metadata]
    Found existing installation: typer 0.20.1━━━━━━━━━━━━━━━━━  8/19 [importlib_metadata]
    Uninstalling typer-0.20.1:━━━━━━━━━━━━━━━━━━━━━━━  8/19 [importlib_metadata]
      Successfully uninstalled typer-0.20.1━━━━━━━━━━━━━━━━━━━  8/19 [importlib_metadata]
  Attempting uninstall: huggingface_hubm╺━━━━━━━━━━━━━━━━ 11/19 [torchvision]ta]
    Found existing installation: huggingface_hub 0.36.2━━━━━━━ 11/19 [torchvision]
    Uninstalling huggingface_hub-0.36.2:0m╺━━━━━━━━━━━━━━ 12/19 [huggingface_hub]

Installing Ollama in Lightning AI Notebook:

Have to install Ollama every run session ends:

In [4]:
!wget https://ollama.com/install.sh
!bash install.sh

--2026-03-08 15:24:27--  https://ollama.com/install.sh
Resolving ollama.com (ollama.com)... 34.36.133.15
Connecting to ollama.com (ollama.com)|34.36.133.15|:443... connected.
HTTP request sent, awaiting response... 307 Temporary Redirect
Location: https://github.com/ollama/ollama/releases/latest/download/install.sh [following]
--2026-03-08 15:24:27--  https://github.com/ollama/ollama/releases/latest/download/install.sh
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/ollama/ollama/releases/download/v0.17.7/install.sh [following]
--2026-03-08 15:24:27--  https://github.com/ollama/ollama/releases/download/v0.17.7/install.sh
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/658928958/537bcc0b-d163-4047-988d-ba7843f803f6?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T15%3A59%3A22Z&rscd=attachment%3B+filename%3Dinstall.sh&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T14%3A58%3A38Z&ske=2026-03-08T15%3A59%3A22Z&sks=b&skv=2018-11-09&sig=8OAi1OYi3bIvVFTsCVAlUlQMyx0j7Cy3eRpz6qphLwM%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk4Mzc2NywibmJmIjoxNzcyOTgzNDY3LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.18YHx4ZhPsPQoWqyWu6zjTBjWTOeSJp_sgfHdbWO3cE&response-content-disposition=attachment%3B%20filename%3Dinstall.sh&response-content-type=application%2Foctet-stream [following]
--2026-03-08 15:24:27--  https://release-assets.githubusercontent.com/github-production-release-asset/658928958/537bcc0b-d163-4047-988d-ba7843f803f6?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T15%3A59%3A22Z&rscd=attachment%3B+filename%3Dinstall.sh&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T14%3A58%3A38Z&ske=2026-03-08T15%3A59%3A22Z&sks=b&skv=2018-11-09&sig=8OAi1OYi3bIvVFTsCVAlUlQMyx0j7Cy3eRpz6qphLwM%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk4Mzc2NywibmJmIjoxNzcyOTgzNDY3LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.18YHx4ZhPsPQoWqyWu6zjTBjWTOeSJp_sgfHdbWO3cE&response-content-disposition=attachment%3B%20filename%3Dinstall.sh&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15902 (16K) [application/octet-stream]
Saving to: ‘install.sh.1’

install.sh.1        100%[===================>]  15.53K  --.-KB/s    in 0s

2026-03-08 15:24:27 (46.5 MB/s) - ‘install.sh.1’ saved [15902/15902]

>>> Installing ollama to /usr/local
>>> Downloading ollama-linux-amd64.tar.zst
######################################################################### 100.0%
>>> Creating ollama user...
>>> Adding ollama user to render group...
>>> Adding ollama user to video group...
>>> Adding current user to ollama group...
>>> Creating ollama systemd service...
>>> Enabling and starting ollama service...
Created symlink /etc/systemd/system/default.target.wants/ollama.service → /etc/systemd/system/ollama.service.
>>> NVIDIA GPU installed.

In [5]:
!ollama --version

]11;?\ollama version is 0.17.7

In [6]:
!ollama pull llama3.1:8b

]11;?\pulling manifest ⠋ pulling manifest ⠙ pulling manifest ⠹ pulling manifest ⠸ pulling manifest ⠼ pulling manifest ⠴ pulling manifest
pulling 667b0c1932bc:   1% ▕                  ▏  27 MB/4.9 GB                  pulling manifest
pulling 667b0c1932bc:   1% ▕                  ▏  45 MB/4.9 GB                  pulling manifest
pulling 667b0c1932bc:   2% ▕                  ▏  91 MB/4.9 GB                  pulling manifest
pulling 667b0c1932bc:   3% ▕                  ▏ 137 MB/4.9 GB                  pulling manifest
pulling 667b0c1932bc:   3% ▕                  ▏ 160 MB/4.9 GB                  pulling manifest
pulling 667b0c1932bc:   5% ▕                  ▏ 222 MB/4.9 GB                  pulling manifest
pulling 667b0c1932bc:   6% ▕█                 ▏ 285 MB/4.9 GB                  pulling manifest
pulling 667b0c1932bc:   6% ▕█                 ▏ 312 MB/4.9 GB                  pulling manifest
pulling 667b0c1932bc:   7% ▕█                 ▏ 364 MB/4.9 GB                  pulling manifest
pulling 667b0c1932bc:   9% ▕█                 ▏ 425 MB/4.9 GB                  pulling manifest
pulling 667b0c1932bc:   9% ▕█                 ▏ 448 MB/4.9 GB  447 MB/s     10spulling manifest
pulling 667b0c1932bc:  10% ▕█                 ▏ 496 MB/4.9 GB  447 MB/s      9spulling manifest
pulling 667b0c1932bc:  11% ▕██                ▏ 552 MB/4.9 GB  447 MB/s      9spulling manifest
pulling 667b0c1932bc:  12% ▕██                ▏ 601 MB/4.9 GB  447 MB/s      9spulling manifest
pulling 667b0c1932bc:  13% ▕██                ▏ 623 MB/4.9 GB  447 MB/s      9spulling manifest
pulling 667b0c1932bc:  14% ▕██                ▏ 672 MB/4.9 GB  447 MB/s      9spulling manifest
pulling 667b0c1932bc:  14% ▕██                ▏ 695 MB/4.9 GB  447 MB/s      9spulling manifest
pulling 667b0c1932bc:  15% ▕██                ▏ 751 MB/4.9 GB  447 MB/s      9spulling manifest
pulling 667b0c1932bc:  16% ▕██                ▏ 797 MB/4.9 GB  447 MB/s      9spulling manifest
pulling 667b0c1932bc:  17% ▕███               ▏ 820 MB/4.9 GB  447 MB/s      9spulling manifest
pulling 667b0c1932bc:  18% ▕███               ▏ 874 MB/4.9 GB  436 MB/s      9spulling manifest
pulling 667b0c1932bc:  18% ▕███               ▏ 899 MB/4.9 GB  436 MB/s      9spulling manifest
pulling 667b0c1932bc:  19% ▕███               ▏ 913 MB/4.9 GB  436 MB/s      9spulling manifest
pulling 667b0c1932bc:  20% ▕███               ▏ 962 MB/4.9 GB  436 MB/s      9spulling manifest
pulling 667b0c1932bc:  20% ▕███               ▏ 1.0 GB/4.9 GB  436 MB/s      8spulling manifest
pulling 667b0c1932bc:  21% ▕███               ▏ 1.0 GB/4.9 GB  436 MB/s      8spulling manifest
pulling 667b0c1932bc:  22% ▕███               ▏ 1.1 GB/4.9 GB  436 MB/s      8spulling manifest
pulling 667b0c1932bc:  23% ▕████              ▏ 1.1 GB/4.9 GB  436 MB/s      8spulling manifest
pulling 667b0c1932bc:  24% ▕████              ▏ 1.2 GB/4.9 GB  436 MB/s      8spulling manifest
pulling 667b0c1932bc:  25% ▕████              ▏ 1.2 GB/4.9 GB  436 MB/s      8spulling manifest
pulling 667b0c1932bc:  26% ▕████              ▏ 1.3 GB/4.9 GB  428 MB/s      8spulling manifest
pulling 667b0c1932bc:  27% ▕████              ▏ 1.3 GB/4.9 GB  428 MB/s      8spulling manifest
pulling 667b0c1932bc:  27% ▕████              ▏ 1.3 GB/4.9 GB  428 MB/s      8spulling manifest
pulling 667b0c1932bc:  28% ▕█████             ▏ 1.4 GB/4.9 GB  428 MB/s      8spulling manifest
pulling 667b0c1932bc:  29% ▕█████             ▏ 1.4 GB/4.9 GB  428 MB/s      8spulling manifest
pulling 667b0c1932bc:  29% ▕█████             ▏ 1.4 GB/4.9 GB  428 MB/s      8spulling manifest
pulling 667b0c1932bc:  30% ▕█████             ▏ 1.5 GB/4.9 GB  428 MB/s      8spulling manifest
pulling 667b0c1932bc:  31% ▕█████             ▏ 1.5 GB/4.9 GB  428 MB/s      7spulling manifest
pulling 667b0c1932bc:  31% ▕█████             ▏ 1.5 GB/4.9 GB  428 MB/s      7spulling manifest
pulling 667b0c1932bc:  32% ▕█████             ▏ 1.6 GB/4.9 GB  428 MB/s      7spulling manifest
pulling 667b0c1932bc:  33% ▕█████             ▏ 1.6 GB/4.9 GB  407 MB/s      8spulling manifest
pulling 667b0c1932bc:  34% ▕██████            ▏ 1.7 GB/4.9 GB  407 MB/s      8spulling manifest
pulling 667b0c1932bc:  35% ▕██████            ▏ 1.7 GB/4.9 GB  407 MB/s      7spulling manifest
pulling 667b0c1932bc:  35% ▕██████            ▏ 1.7 GB/4.9 GB  407 MB/s      7spulling manifest
pulling 667b0c1932bc:  36% ▕██████            ▏ 1.8 GB/4.9 GB  407 MB/s      7spulling manifest
pulling 667b0c1932bc:  37% ▕██████            ▏ 1.8 GB/4.9 GB  407 MB/s      7spulling manifest
pulling 667b0c1932bc:  38% ▕██████            ▏ 1.9 GB/4.9 GB  407 MB/s      7spulling manifest
pulling 667b0c1932bc:  39% ▕██████            ▏ 1.9 GB/4.9 GB  407 MB/s      7spulling manifest
pulling 667b0c1932bc:  40% ▕███████           ▏ 2.0 GB/4.9 GB  407 MB/s      7spulling manifest
pulling 667b0c1932bc:  41% ▕███████           ▏ 2.0 GB/4.9 GB  407 MB/s      7spulling manifest
pulling 667b0c1932bc:  42% ▕███████           ▏ 2.0 GB/4.9 GB  407 MB/s      7spulling manifest
pulling 667b0c1932bc:  43% ▕███████           ▏ 2.1 GB/4.9 GB  414 MB/s      6spulling manifest
pulling 667b0c1932bc:  43% ▕███████           ▏ 2.1 GB/4.9 GB  414 MB/s      6spulling manifest
pulling 667b0c1932bc:  44% ▕███████           ▏ 2.2 GB/4.9 GB  414 MB/s      6spulling manifest
pulling 667b0c1932bc:  45% ▕████████          ▏ 2.2 GB/4.9 GB  414 MB/s      6spulling manifest
pulling 667b0c1932bc:  46% ▕████████          ▏ 2.2 GB/4.9 GB  414 MB/s      6spulling manifest
pulling 667b0c1932bc:  47% ▕████████          ▏ 2.3 GB/4.9 GB  414 MB/s      6spulling manifest
pulling 667b0c1932bc:  48% ▕████████          ▏ 2.3 GB/4.9 GB  414 MB/s      6spulling manifest
pulling 667b0c1932bc:  48% ▕████████          ▏ 2.4 GB/4.9 GB  414 MB/s      6spulling manifest
pulling 667b0c1932bc:  49% ▕████████          ▏ 2.4 GB/4.9 GB  414 MB/s      6spulling manifest
pulling 667b0c1932bc:  51% ▕█████████         ▏ 2.5 GB/4.9 GB  414 MB/s      5spulling manifest
pulling 667b0c1932bc:  51% ▕█████████         ▏ 2.5 GB/4.9 GB  419 MB/s      5spulling manifest
pulling 667b0c1932bc:  52% ▕█████████         ▏ 2.6 GB/4.9 GB  419 MB/s      5spulling manifest
pulling 667b0c1932bc:  53% ▕█████████         ▏ 2.6 GB/4.9 GB  419 MB/s      5spulling manifest
pulling 667b0c1932bc:  54% ▕█████████         ▏ 2.7 GB/4.9 GB  419 MB/s      5spulling manifest
pulling 667b0c1932bc:  55% ▕█████████         ▏ 2.7 GB/4.9 GB  419 MB/s      5spulling manifest
pulling 667b0c1932bc:  56% ▕██████████        ▏ 2.8 GB/4.9 GB  419 MB/s      5spulling manifest
pulling 667b0c1932bc:  57% ▕██████████        ▏ 2.8 GB/4.9 GB  419 MB/s      5spulling manifest
pulling 667b0c1932bc:  58% ▕██████████        ▏ 2.8 GB/4.9 GB  419 MB/s      4spulling manifest
pulling 667b0c1932bc:  59% ▕██████████        ▏ 2.9 GB/4.9 GB  419 MB/s      4spulling manifest
pulling 667b0c1932bc:  59% ▕██████████        ▏ 2.9 GB/4.9 GB  419 MB/s      4spulling manifest
pulling 667b0c1932bc:  60% ▕██████████        ▏ 3.0 GB/4.9 GB  424 MB/s      4spulling manifest
pulling 667b0c1932bc:  61% ▕███████████       ▏ 3.0 GB/4.9 GB  424 MB/s      4spulling manifest
pulling 667b0c1932bc:  62% ▕███████████       ▏ 3.0 GB/4.9 GB  424 MB/s      4spulling manifest
pulling 667b0c1932bc:  63% ▕███████████       ▏ 3.1 GB/4.9 GB  424 MB/s      4spulling manifest
pulling 667b0c1932bc:  64% ▕███████████       ▏ 3.1 GB/4.9 GB  424 MB/s      4spulling manifest
pulling 667b0c1932bc:  64% ▕███████████       ▏ 3.2 GB/4.9 GB  424 MB/s      4spulling manifest
pulling 667b0c1932bc:  65% ▕███████████       ▏ 3.2 GB/4.9 GB  424 MB/s      4spulling manifest
pulling 667b0c1932bc:  67% ▕███████████       ▏ 3.3 GB/4.9 GB  424 MB/s      3spulling manifest
pulling 667b0c1932bc:  67% ▕████████████      ▏ 3.3 GB/4.9 GB  424 MB/s      3spulling manifest
pulling 667b0c1932bc:  68% ▕████████████      ▏ 3.4 GB/4.9 GB  424 MB/s      3spulling manifest
pulling 667b0c1932bc:  69% ▕████████████      ▏ 3.4 GB/4.9 GB  425 MB/s      3spulling manifest
pulling 667b0c1932bc:  70% ▕████████████      ▏ 3.4 GB/4.9 GB  425 MB/s      3spulling manifest
pulling 667b0c1932bc:  71% ▕████████████      ▏ 3.5 GB/4.9 GB  425 MB/s      3spulling manifest
pulling 667b0c1932bc:  72% ▕████████████      ▏ 3.5 GB/4.9 GB  425 MB/s      3spulling manifest
pulling 667b0c1932bc:  72% ▕████████████      ▏ 3.5 GB/4.9 GB  425 MB/s      3spulling manifest
pulling 667b0c1932bc:  73% ▕█████████████     ▏ 3.6 GB/4.9 GB  425 MB/s      3spulling manifest
pulling 667b0c1932bc:  74% ▕█████████████     ▏ 3.6 GB/4.9 GB  425 MB/s      3spulling manifest
pulling 667b0c1932bc:  75% ▕█████████████     ▏ 3.7 GB/4.9 GB  425 MB/s      2spulling manifest
pulling 667b0c1932bc:  76% ▕█████████████     ▏ 3.7 GB/4.9 GB  425 MB/s      2spulling manifest
pulling 667b0c1932bc:  77% ▕█████████████     ▏ 3.8 GB/4.9 GB  425 MB/s      2spulling manifest
pulling 667b0c1932bc:  78% ▕██████████████    ▏ 3.8 GB/4.9 GB  425 MB/s      2spulling manifest
pulling 667b0c1932bc:  80% ▕██████████████    ▏ 3.9 GB/4.9 GB  430 MB/s      2spulling manifest
pulling 667b0c1932bc:  81% ▕██████████████    ▏ 4.0 GB/4.9 GB  430 MB/s      2spulling manifest
pulling 667b0c1932bc:  82% ▕██████████████    ▏ 4.0 GB/4.9 GB  430 MB/s      2spulling manifest
pulling 667b0c1932bc:  83% ▕██████████████    ▏ 4.1 GB/4.9 GB  430 MB/s      1spulling manifest
pulling 667b0c1932bc:  84% ▕███████████████   ▏ 4.1 GB/4.9 GB  430 MB/s      1spulling manifest
pulling 667b0c1932bc:  85% ▕███████████████   ▏ 4.2 GB/4.9 GB  430 MB/s      1spulling manifest
pulling 667b0c1932bc:  86% ▕███████████████   ▏ 4.2 GB/4.9 GB  430 MB/s      1spulling manifest
pulling 667b0c1932bc:  87% ▕███████████████   ▏ 4.3 GB/4.9 GB  430 MB/s      1spulling manifest
pulling 667b0c1932bc:  88% ▕███████████████   ▏ 4.3 GB/4.9 GB  430 MB/s      1spulling manifest
pulling 667b0c1932bc:  89% ▕████████████████  ▏ 4.4 GB/4.9 GB  430 MB/s      1spulling manifest
pulling 667b0c1932bc:  90% ▕████████████████  ▏ 4.4 GB/4.9 GB  439 MB/s      1spulling manifest
pulling 667b0c1932bc:  91% ▕████████████████  ▏ 4.5 GB/4.9 GB  439 MB/s      0spulling manifest
pulling 667b0c1932bc:  92% ▕████████████████  ▏ 4.5 GB/4.9 GB  439 MB/s      0spulling manifest
pulling 667b0c1932bc:  93% ▕████████████████  ▏ 4.6 GB/4.9 GB  439 MB/s      0spulling manifest
pulling 667b0c1932bc:  93% ▕████████████████  ▏ 4.6 GB/4.9 GB  439 MB/s      0spulling manifest
pulling 667b0c1932bc:  95% ▕█████████████████ ▏ 4.7 GB/4.9 GB  439 MB/s      0spulling manifest
pulling 667b0c1932bc:  95% ▕█████████████████ ▏ 4.7 GB/4.9 GB  439 MB/s      0spulling manifest
pulling 667b0c1932bc:  96% ▕█████████████████ ▏ 4.7 GB/4.9 GB  439 MB/s      0spulling manifest
pulling 667b0c1932bc:  97% ▕█████████████████ ▏ 4.8 GB/4.9 GB  439 MB/s      0spulling manifest
pulling 667b0c1932bc:  97% ▕█████████████████ ▏ 4.8 GB/4.9 GB  439 MB/s      0spulling manifest
pulling 667b0c1932bc:  98% ▕█████████████████ ▏ 4.8 GB/4.9 GB  437 MB/s      0spulling manifest
pulling 667b0c1932bc:  99% ▕█████████████████ ▏ 4.8 GB/4.9 GB  437 MB/s      0spulling manifest
pulling 667b0c1932bc:  99% ▕█████████████████ ▏ 4.9 GB/4.9 GB  437 MB/s      0spulling manifest
pulling 667b0c1932bc:  99% ▕█████████████████ ▏ 4.9 GB/4.9 GB  437 MB/s      0spulling manifest
pulling 667b0c1932bc: 100% ▕█████████████████ ▏ 4.9 GB/4.9 GB  437 MB/s      0spulling manifest
pulling 667b0c1932bc: 100% ▕█████████████████ ▏ 4.9 GB/4.9 GB  437 MB/s      0spulling manifest
pulling 667b0c1932bc: 100% ▕█████████████████ ▏ 4.9 GB/4.9 GB  437 MB/s      0spulling manifest
pulling 667b0c1932bc: 100% ▕█████████████████ ▏ 4.9 GB/4.9 GB  437 MB/s      0spulling manifest
pulling 667b0c1932bc: 100% ▕█████████████████ ▏ 4.9 GB/4.9 GB  437 MB/s      0spulling manifest
pulling 667b0c1932bc: 100% ▕█████████████████ ▏ 4.9 GB/4.9 GB  437 MB/s      0spulling manifest
pulling 667b0c1932bc: 100% ▕█████████████████ ▏ 4.9 GB/4.9 GB  402 MB/s      0spulling manifest
pulling 667b0c1932bc: 100% ▕█████████████████ ▏ 4.9 GB/4.9 GB  402 MB/s      0spulling manifest
pulling 667b0c1932bc: 100% ▕█████████████████ ▏ 4.9 GB/4.9 GB  402 MB/s      0spulling manifest
pulling 667b0c1932bc: 100% ▕█████████████████ ▏ 4.9 GB/4.9 GB  402 MB/s      0spulling manifest
pulling 667b0c1932bc: 100% ▕█████████████████ ▏ 4.9 GB/4.9 GB  402 MB/s      0spulling manifest
pulling 667b0c1932bc: 100% ▕█████████████████ ▏ 4.9 GB/4.9 GB  402 MB/s      0spulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB
pulling 0ba8f0e314b4: 100% ▕██████████████████▏  12 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB
pulling 0ba8f0e314b4: 100% ▕██████████████████▏  12 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB
pulling 0ba8f0e314b4: 100% ▕██████████████████▏  12 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB
pulling 0ba8f0e314b4: 100% ▕██████████████████▏  12 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB
pulling 0ba8f0e314b4: 100% ▕██████████████████▏  12 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB
pulling 0ba8f0e314b4: 100% ▕██████████████████▏  12 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB
pulling 0ba8f0e314b4: 100% ▕██████████████████▏  12 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB
pulling 0ba8f0e314b4: 100% ▕██████████████████▏  12 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB
pulling 0ba8f0e314b4: 100% ▕██████████████████▏  12 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB
pulling 0ba8f0e314b4: 100% ▕██████████████████▏  12 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB
pulling 0ba8f0e314b4: 100% ▕██████████████████▏  12 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB
pulling 0ba8f0e314b4: 100% ▕██████████████████▏  12 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB
pulling 0ba8f0e314b4: 100% ▕██████████████████▏  12 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB
pulling 0ba8f0e314b4: 100% ▕██████████████████▏  12 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB
pulling 0ba8f0e314b4: 100% ▕██████████████████▏  12 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB
pulling 0ba8f0e314b4: 100% ▕██████████████████▏  12 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB
pulling 0ba8f0e314b4: 100% ▕██████████████████▏  12 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB
pulling 0ba8f0e314b4: 100% ▕██████████████████▏  12 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB
pulling 0ba8f0e314b4: 100% ▕██████████████████▏  12 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB
pulling 0ba8f0e314b4: 100% ▕██████████████████▏  12 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB
pulling 0ba8f0e314b4: 100% ▕██████████████████▏  12 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB
pulling 0ba8f0e314b4: 100% ▕██████████████████▏  12 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB
pulling 0ba8f0e314b4: 100% ▕██████████████████▏  12 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB
pulling 0ba8f0e314b4: 100% ▕██████████████████▏  12 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB
pulling 0ba8f0e314b4: 100% ▕██████████████████▏  12 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB
pulling 0ba8f0e314b4: 100% ▕██████████████████▏  12 KB                         pulling manifest
pulling 667b0c1932bc: 100% ▕██████████████████▏ 4.9 GB
pulling 948af2743fc7: 100% ▕██████████████████▏ 1.5 KB

In [1]:
#!pip install nest_asyncio

Requirement already satisfied: nest_asyncio in /home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages (1.6.0)

Start/Re-start Ollama:

In [7]:
!ls /usr/local/bin/ollama

/usr/local/bin/ollama

In [8]:
!ollama serve

]11;?\Error: listen tcp 127.0.0.1:11434: bind: address already in use

In [9]:
import sys
# Ensure we aren't accidentally pulling from Roaming
sys.path = [p for p in sys.path if "Roaming" not in p]

try:
    from scipy import sparse
    import sklearn
    print("Success! Scipy Sparse and Sklearn are both loaded.")
except ImportError as e:
    print(f"Still failing: {e}")

Success! Scipy Sparse and Sklearn are both loaded.

In [17]:
import unsloth
import json
from datasets import Dataset
import sys
from unsloth import FastLanguageModel
from trl import SFTTrainer, SFTConfig, GRPOConfig, GRPOTrainer
import torch

import os
from dotenv import load_dotenv
load_dotenv()

True

In [18]:
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_openai import ChatOpenAI
from langchain_core.prompts import PromptTemplate
#from langchain_community.chains import LLMChain
import json
from langchain_community.llms import Ollama
from langchain_community.chat_models import ChatOllama
import os
import urllib.request
from pathlib import Path
from dotenv import load_dotenv
from sklearn.model_selection import train_test_split
import pandas as pd
from langchain_core.documents import Document
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import OllamaEmbeddings, OpenAIEmbeddings
#from langchain.evaluation import load_evaluator
from datasets import Dataset
from ragas.metrics.collections import (
    faithfulness,
    answer_relevancy,
    context_precision,
    context_recall,
)
from ragas.llms import LangchainLLMWrapper
from datasets import load_dataset
from langchain_core.prompts import ChatPromptTemplate, PromptTemplate
from ragas import evaluate
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from ragas.metrics import Faithfulness, AnswerRelevancy, AnswerCorrectness, ContextUtilization, ContextPrecision
from openai import OpenAI
from ragas.llms import llm_factory
from ragas.embeddings import embedding_factory
from ragas.metrics.base import Metric
from langchain_experimental.text_splitter import SemanticChunker

import random
from typing import List
from pydantic import BaseModel
from langchain_core.output_parsers import PydanticOutputParser, JsonOutputParser
from prompts import  RFT_EVAL_DATA_GEN_CONCISE

from pydantic import BaseModel, Field
from langchain_community.vectorstores import FAISS
#import faiss
from langchain_community.docstore.in_memory import InMemoryDocstore
from IPython.display import display, Markdown
#from transformers import TrainingArguments

import gc
import re
load_dotenv()

/tmp/ipykernel_3710/614624552.py:32: DeprecationWarning: Importing Faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import Faithfulness
  from ragas.metrics import Faithfulness, AnswerRelevancy, AnswerCorrectness, ContextUtilization, ContextPrecision
/tmp/ipykernel_3710/614624552.py:32: DeprecationWarning: Importing AnswerRelevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import AnswerRelevancy
  from ragas.metrics import Faithfulness, AnswerRelevancy, AnswerCorrectness, ContextUtilization, ContextPrecision
/tmp/ipykernel_3710/614624552.py:32: DeprecationWarning: Importing AnswerCorrectness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import AnswerCorrectness
  from ragas.metrics import Faithfulness, AnswerRelevancy, AnswerCorrectness, ContextUtilization, ContextPrecision
/tmp/ipykernel_3710/614624552.py:32: DeprecationWarning: Importing ContextUtilization from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import ContextUtilization
  from ragas.metrics import Faithfulness, AnswerRelevancy, AnswerCorrectness, ContextUtilization, ContextPrecision
/tmp/ipykernel_3710/614624552.py:32: DeprecationWarning: Importing ContextPrecision from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import ContextPrecision
  from ragas.metrics import Faithfulness, AnswerRelevancy, AnswerCorrectness, ContextUtilization, ContextPrecision

True

In [12]:
print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"CUDA version: {torch.version.cuda}")
    print(f"GPU: {torch.cuda.get_device_name(0)}")

PyTorch version: 2.10.0+cu128
CUDA available: True
CUDA version: 12.8
GPU: Tesla T4

In [13]:
import torch
print(f"PyTorch CUDA: {torch.version.cuda}")
print(torch.cuda.get_device_capability())
!nvcc --version

PyTorch CUDA: 12.8
(7, 5)

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Oct_29_23:50:19_PDT_2024
Cuda compilation tools, release 12.6, V12.6.85
Build cuda_12.6.r12.6/compiler.35059454_0

In [8]:
!nvidia-smi

Sat Mar  7 15:53:10 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.211.01             Driver Version: 570.211.01     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:1E.0 Off |                    0 |
| N/A   22C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

##### SmallThoughts dataset is used as an evaluation dataset. We are using the "test" split for evaluation.

Loading the dataset for evaluation:

In [19]:
smallThoughts_dataset = load_dataset("SmallDoge/SmallThoughts")
smallThoughts_eval_dataset = smallThoughts_dataset['test']
smallThoughts_eval_dataset

Dataset({
    features: ['problem', 'solution', 'messages', 'system_prompt'],
    num_rows: 2000
})

Let's check out the dataset:

In [10]:
print("Checking the Problem :")
display(Markdown(smallThoughts_eval_dataset[:1]['problem'][0]))
print("Checking the Solution :")
display(Markdown(smallThoughts_eval_dataset[:1]['solution'][0]))
print("Checking the Messages :")
display(Markdown(smallThoughts_eval_dataset[:1]['messages'][0][0]['content']))
print("Checking the System Prompt :")
display(Markdown(smallThoughts_eval_dataset[:1]['system_prompt'][0]))

Checking the Problem :

Return your final response within \boxed{}. Given the function \( y = f(x) \) which has an inverse function \( y = f^{-1}(x) \), what is the equation of the curve obtained after rotating the graph of \( y = f(x) \) counterclockwise by \( 90^{\circ} \) around the point \( (1, -1) \)?

(A) \( y = f^{-1}(-x) - 2 \)
(B) \( y = -f^{-1}(-x) - 2 \)
(C) \( y = f^{-1}(-x + 1) - 1 \)
(D) \( y = f^{-1}(-x - 1) + 1 \)

Checking the Solution :

**Solution:**
To determine the equation of the curve after rotating \( y = f(x) \) 90° counterclockwise around \( (1, -1) \):

1. **Translate the point \( (t, f(t)) \) to the origin-centered system**:
   \[
   (t - 1, f(t) + 1)
   \]
2. **Apply 90° counterclockwise rotation** (transforms \( (a, b) \to (-b, a) \)):
   \[
   (- (f(t) + 1), t - 1)
   \]
3. **Translate back to the original coordinate system**:
   \[
   (-f(t) - 1 + 1, t - 1 - 1) = (-f(t), t - 2)
   \]
4. **Relabel the rotated coordinates as \( (x, y) \)**:
   \[
   x = -f(t) \quad \Rightarrow \quad t = f^{-1}(-x)
   \]
   Substitute \( t \) into \( y = t - 2 \):
   \[
   y = f^{-1}(-x) - 2
   \]

Thus, the transformed equation is \( y = f^{-1}(-x) - 2 \), making the correct answer \(\boxed{\text{A}}\).

Checking the Messages :

Return your final response within \boxed{}. Given the function \( y = f(x) \) which has an inverse function \( y = f^{-1}(x) \), what is the equation of the curve obtained after rotating the graph of \( y = f(x) \) counterclockwise by \( 90^{\circ} \) around the point \( (1, -1) \)?

(A) \( y = f^{-1}(-x) - 2 \)
(B) \( y = -f^{-1}(-x) - 2 \)
(C) \( y = f^{-1}(-x + 1) - 1 \)
(D) \( y = f^{-1}(-x - 1) + 1 \)

Checking the System Prompt :

As an assistant, you need to first assess the complexity of the problem and adopt an appropriate thinking framework before providing the final solution. Structure your response into two main sections: Thought and Solution.
First evaluate the complexity of the problem, then choose a suitable thinking framework, and describe the thought process as detailed as possible:
1. For simple problems:
**Analysis:**
[Understand the core elements and goals of the problem]
**Approach:**
[Propose direct solution methods]
**Summary:**
[Concisely summarize the solution approach and key points]
2. For moderately complex problems:
**Analysis:**
[Understand the problem and identify key points and challenges]
**Initial Approach:**
[Propose preliminary solutions]
**Reflection:**
[Evaluate the pros and cons of the initial approach]
**Improvement:**
[Refine the solution based on reflection]
**Summary:**
[Summarize the key points of the final solution]
3. For highly complex problems:
**Analysis:**
[Analyze various aspects of the problem and break down its structure]
**Problem Decomposition:**
[Break complex problem into manageable sub-problems]
**Sub-problem Processing:** (Repeat the following steps for each sub-problem)
- Sub-problem 1:
  * Initial approach
  * Reflection
  * Improved solution
- Sub-problem 2:
  * Initial approach
  * Reflection
  * Improved solution
- ...(adjust according to the actual number of sub-problems)
**Integration:**
[Integrate sub-problem solutions into a complete solution]
**Overall Reflection:**
[Evaluate the integrated complete solution]
**Final Optimization:**
[Make final optimizations based on overall reflection]
**Summary:**
[Summarize key points of the final comprehensive solution]
The solution section should maintain logical, accurate, and concise expression, detailing the steps needed to reach the conclusion, formatted as:
**Solution:**
[Provide the final solution here]

We feed the 'questions' to the base model (Llama3.1-8b) and record the generated answers. We use RAGAS and GPT4o to evaluate the answers to set the baseline scores of Faithfulness, Answer Relevancy and Answer Correctness

Prepare the dataset in the format expected by RAGAS for evaluation:

In [21]:
openai_api_key = os.getenv("OPENAI_API_KEY")

In [20]:
#Define the model we aim to fine-tune:
ft_model = ChatOllama(
    model="llama3.1:8b",
    temperature=0,
    num_predict=1024,      
    repeat_penalty=1.2,
    timeout=60            
)

/tmp/ipykernel_3710/3481607908.py:2: LangChainDeprecationWarning: The class `ChatOllama` was deprecated in LangChain 0.3.1 and will be removed in 1.0.0. An updated version of the class exists in the `langchain-ollama package and should be used instead. To use it run `pip install -U `langchain-ollama` and import as `from `langchain_ollama import ChatOllama``.
  ft_model = ChatOllama(

In [22]:
class RFTEvalDataset(BaseModel):
    
    thought: str = Field(description="The detailed thinking process and complexity analysis")
    solution: str = Field(description="The step-by-step final mathematical solution")

In [23]:
def custom_parser(text: str) -> RFTEvalDataset:
    """Manually extracts tags since with_structured_output is missing."""
    thought_match = re.search(r'<thought>(.*?)</thought>', text, re.DOTALL)
    solution_match = re.search(r'(?i)<solution\s*>(.*?)</solution\s*>', text, re.DOTALL)
    
    return RFTEvalDataset(
        thought=thought_match.group(1).strip() if thought_match else "Parsing Error",
        solution=solution_match.group(1).strip() if solution_match else text # Fallback to raw text
    )

def generate_answers(dataset, sample_size = 10):
    
    rft_eval_data = []

    prompt = PromptTemplate(
                            template=RFT_EVAL_DATA_GEN_CONCISE,
                            input_variables = ["problem"]
                            )
    
    #structured_llm = ft_model.with_structured_output(RFTEvalDataset)
    rft_chain = prompt | ft_model

    #Selecting 20 rows for evaluation:
    data = dataset.select(range(sample_size))
    print(f"Total Evaluation Samples : {len(data)}")

    for idx, row in enumerate(data):
    
        try:

            print(f"Processing Sample {idx+1}. Problem length: {len(row['problem'])}")
            
            res = rft_chain.invoke(input={'problem':row['problem']})

            structured_output = custom_parser(res.content)

            rft_eval_data.append({
                "question" : row['problem'],
                "contexts" : [row['solution']],
                "ground_truth" : row['solution'],
                "thought" : structured_output.thought,
                "answer" : structured_output.solution,
            })

            gc.collect()
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

            print(f"Generation Completed for Sample : {idx+1}")
        
        except Exception as e:
            print(f"FAILED at Sample {idx+1}: {str(e)}")
            continue 

    #Saving the answer to csv:
    test_generated_dataset = pd.DataFrame.from_records(data=rft_eval_data)
    test_generated_dataset.to_csv("../data/testEvalData_rft_baseModel.csv",index=False)

    #Converting to Huggingface Dataset format for RAGAS evaluation:
    rft_eval_data = Dataset.from_list(rft_eval_data)
    return rft_eval_data

In [24]:
rft_eval_data = generate_answers(smallThoughts_eval_dataset, sample_size = 50)
rft_eval_data

Total Evaluation Samples : 50
Processing Sample 1. Problem length: 415

Generation Completed for Sample : 1
Processing Sample 2. Problem length: 260
Generation Completed for Sample : 2
Processing Sample 3. Problem length: 92
Generation Completed for Sample : 3
Processing Sample 4. Problem length: 237
Generation Completed for Sample : 4
Processing Sample 5. Problem length: 258
Generation Completed for Sample : 5
Processing Sample 6. Problem length: 254
Generation Completed for Sample : 6
Processing Sample 7. Problem length: 258
Generation Completed for Sample : 7
Processing Sample 8. Problem length: 154
Generation Completed for Sample : 8
Processing Sample 9. Problem length: 1221
Generation Completed for Sample : 9
Processing Sample 10. Problem length: 358
Generation Completed for Sample : 10
Processing Sample 11. Problem length: 226
Generation Completed for Sample : 11
Processing Sample 12. Problem length: 150
Generation Completed for Sample : 12
Processing Sample 13. Problem length: 253
Generation Completed for Sample : 13
Processing Sample 14. Problem length: 169
Generation Completed for Sample : 14
Processing Sample 15. Problem length: 181
Generation Completed for Sample : 15
Processing Sample 16. Problem length: 209
Generation Completed for Sample : 16
Processing Sample 17. Problem length: 239
Generation Completed for Sample : 17
Processing Sample 18. Problem length: 234
Generation Completed for Sample : 18
Processing Sample 19. Problem length: 458
Generation Completed for Sample : 19
Processing Sample 20. Problem length: 2505
Generation Completed for Sample : 20
Processing Sample 21. Problem length: 193
Generation Completed for Sample : 21
Processing Sample 22. Problem length: 125
Generation Completed for Sample : 22
Processing Sample 23. Problem length: 253
Generation Completed for Sample : 23
Processing Sample 24. Problem length: 311
Generation Completed for Sample : 24
Processing Sample 25. Problem length: 190
Generation Completed for Sample : 25
Processing Sample 26. Problem length: 252
Generation Completed for Sample : 26
Processing Sample 27. Problem length: 139
Generation Completed for Sample : 27
Processing Sample 28. Problem length: 244
Generation Completed for Sample : 28
Processing Sample 29. Problem length: 154
Generation Completed for Sample : 29
Processing Sample 30. Problem length: 230
Generation Completed for Sample : 30
Processing Sample 31. Problem length: 229
Generation Completed for Sample : 31
Processing Sample 32. Problem length: 302
Generation Completed for Sample : 32
Processing Sample 33. Problem length: 187
Generation Completed for Sample : 33
Processing Sample 34. Problem length: 231
Generation Completed for Sample : 34
Processing Sample 35. Problem length: 217
Generation Completed for Sample : 35
Processing Sample 36. Problem length: 115
Generation Completed for Sample : 36
Processing Sample 37. Problem length: 305
Generation Completed for Sample : 37
Processing Sample 38. Problem length: 240
Generation Completed for Sample : 38
Processing Sample 39. Problem length: 298
Generation Completed for Sample : 39
Processing Sample 40. Problem length: 310
Generation Completed for Sample : 40
Processing Sample 41. Problem length: 227
Generation Completed for Sample : 41
Processing Sample 42. Problem length: 180
Generation Completed for Sample : 42
Processing Sample 43. Problem length: 131
Generation Completed for Sample : 43
Processing Sample 44. Problem length: 164
Generation Completed for Sample : 44
Processing Sample 45. Problem length: 149
Generation Completed for Sample : 45
Processing Sample 46. Problem length: 450
Generation Completed for Sample : 46
Processing Sample 47. Problem length: 1646
Generation Completed for Sample : 47
Processing Sample 48. Problem length: 194
Generation Completed for Sample : 48
Processing Sample 49. Problem length: 3225
Generation Completed for Sample : 49
Processing Sample 50. Problem length: 339
Generation Completed for Sample : 50

Dataset({
    features: ['question', 'contexts', 'ground_truth', 'thought', 'answer'],
    num_rows: 50
})

In [25]:
rft_base_eval_data = pd.read_csv("../data/testEvalData_rft_baseModel.csv")
print(f"Shape of Eval Data : {rft_base_eval_data.shape}")
rft_base_eval_data.head()

Shape of Eval Data : (50, 5)

,question,contexts,ground_truth,thought,answer
0,Return your final response within \boxed{}. Gi...,['**Solution:**\nTo determine the equation of ...,**Solution:**\nTo determine the equation of th...,**Analysis:** The problem involves a function ...,<thought>\n **Analysis:** The problem invol...
1,Return your final response within \boxed{}. Pr...,['**Solution:**\n\nTo prove the inequality:\n\...,**Solution:**\n\nTo prove the inequality:\n\[\...,**Analysis:** The problem involves proving an ...,<thought>\n **Analysis:** The problem invol...
2,Return your final response within \boxed{}. If...,['**Solution:**\nGiven the equation \\(\\log_2...,**Solution:**\nGiven the equation \(\log_2 x^2...,Parsing Error,<thought>\n **Analysis:** The problem invol...
3,Return your final response within \boxed{}. A ...,['**Solution:**\n1. The original ratio of butt...,**Solution:**\n1. The original ratio of butter...,**Analysis:** The problem involves a proportio...,<thought>\n **Analysis:** The problem invol...
4,Return your final response within \boxed{}. Gi...,['**Solution:**\n\n1. **Separate the integer p...,**Solution:**\n\n1. **Separate the integer par...,**Analysis:** The problem involves converting ...,<thought>\n **Analysis:** The problem invol...

In [26]:
def parse_answers(text):
    # Added (?i) for case-insensitivity and \s* for potential spaces
    solution_match = re.search(r'(?i)<solution\s*>(.*?)</solution\s*>', text, re.DOTALL)
    
    if solution_match:
        return solution_match.group(1).strip()
    
    # If the tag wasn't closed properly, try to grab everything after the opening tag
    fallback_match = re.search(r'(?i)<solution\s*>(.*)', text, re.DOTALL)
    if fallback_match:
        return fallback_match.group(1).strip()
        
    return text

rft_base_eval_data['parsed_answer'] = rft_base_eval_data['answer'].apply(parse_answers)
rft_base_eval_data.head()

,question,contexts,ground_truth,thought,answer,parsed_answer
0,Return your final response within \boxed{}. Gi...,['**Solution:**\nTo determine the equation of ...,**Solution:**\nTo determine the equation of th...,**Analysis:** The problem involves a function ...,<thought>\n **Analysis:** The problem invol...,**Goal:** Find the equation of the curve obtai...
1,Return your final response within \boxed{}. Pr...,['**Solution:**\n\nTo prove the inequality:\n\...,**Solution:**\n\nTo prove the inequality:\n\[\...,**Analysis:** The problem involves proving an ...,<thought>\n **Analysis:** The problem invol...,Goal: Prove the inequality involving real numb...
2,Return your final response within \boxed{}. If...,['**Solution:**\nGiven the equation \\(\\log_2...,**Solution:**\nGiven the equation \(\log_2 x^2...,Parsing Error,<thought>\n **Analysis:** The problem invol...,<thought>\n **Analysis:** The problem invol...
3,Return your final response within \boxed{}. A ...,['**Solution:**\n1. The original ratio of butt...,**Solution:**\n1. The original ratio of butter...,**Analysis:** The problem involves a proportio...,<thought>\n **Analysis:** The problem invol...,Goal: Find the required amount of butter for a...
4,Return your final response within \boxed{}. Gi...,['**Solution:**\n\n1. **Separate the integer p...,**Solution:**\n\n1. **Separate the integer par...,**Analysis:** The problem involves converting ...,<thought>\n **Analysis:** The problem invol...,The goal is to rewrite the fraction \( \frac{1...

In [44]:
print(rft_base_eval_data['ground_truth'][0])

**Solution:**

Given isosceles \(\triangle ABC\) with \(AB = BC\), median \(AD\), and angle bisector \(CE\) perpendicular to each other:

1. **Triangle Setup**:
   - Let \(AB = BC = 2a\), \(D\) as the midpoint of \(BC\) (\(BD = DC = a\)).
   - \(\angle C = \alpha\), split by \(CE\) into \(\alpha/2\).

2. **Key Relationships**:
   - Using the Law of Cosines in \(\triangle ABC\):
     \[
     \cos \alpha = \frac{1}{4} \implies \alpha = \arccos\left(\frac{1}{4}\right).
     \]

3. **Trigonometric Identities**:
   - Compute \(\sin \frac{\alpha}{2}\) and \(\cos \frac{\alpha}{2}\):
     \[
     \sin \frac{\alpha}{2} = \sqrt{\frac{1 - \cos \alpha}{2}} = \frac{\sqrt{6}}{4}, \quad \cos \frac{\alpha}{2} = \frac{\sqrt{10}}{4}.
     \]

4. **Angle Calculation**:
   - \(\angle ADB\) involves \(\cos(90^\circ + \frac{\alpha}{2}) = -\sin \frac{\alpha}{2}\):
     \[
     \angle ADB = 180^\circ - \arccos\left(\frac{\sqrt{6}}{4}\right).
     \]

\[
\boxed{180^\circ - \arccos \left(\frac{\sqrt{6}}{4}\right)}
\]

In [45]:
print(rft_base_eval_data['thought'][0])

**Analysis:** The problem involves finding a specific angle in an isosceles triangle where both the median and the angle bisector intersect perpendicularly, indicating right angles at these intersection points.

        **Initial Approach:**
            - Recognize that since $AB = BC$, $\triangle ABC$ is indeed isosceles.
            - Note that because $AD$ is a median to side $BC$, it divides this side into two equal segments ($BD=DC$).
            - Since the angle bisector of an angle in a triangle intersects the opposite side and forms right angles with medians at their intersection points, we can infer properties about $\triangle ADE$.

        **Reflection:**
            - The fact that $CE$ is perpendicular to both $AD$ and itself implies it's also perpendicular to any line parallel or coincident with these lines.
            - This means the angle between $AE$ (or $AC$, since they're equal in length due to being sides of an equilateral triangle formed by intersecting medians) and $DE$ is a right angle.

        **Improvement:**
            - Since $\triangle AED$ has two known angles ($\angle EAD = 45^\circ$ from the perpendicular intersection, and another angle that's part of the original triangle), we can find its third.
            - Knowing this information allows us to calculate other relevant angles in the problem.

        **Summary:** The goal is to determine $\angle ADB$, which involves understanding relationships within an isosceles triangle where medians intersect perpendicularly with angle bisectors, indicating right-angled triangles and equal side lengths due to symmetry.

In [46]:
print(rft_base_eval_data['answer'][0])

<thought>
        **Analysis:** The problem involves finding a specific angle in an isosceles triangle where both the median and the angle bisector intersect perpendicularly, indicating right angles at these intersection points.

        **Initial Approach:**
            - Recognize that since $AB = BC$, $\triangle ABC$ is indeed isosceles.
            - Note that because $AD$ is a median to side $BC$, it divides this side into two equal segments ($BD=DC$).
            - Since the angle bisector of an angle in a triangle intersects the opposite side and forms right angles with medians at their intersection points, we can infer properties about $\triangle ADE$.

        **Reflection:**
            - The fact that $CE$ is perpendicular to both $AD$ and itself implies it's also perpendicular to any line parallel or coincident with these lines.
            - This means the angle between $AE$ (or $AC$, since they're equal in length due to being sides of an equilateral triangle formed by intersecting medians) and $DE$ is a right angle.

        **Improvement:**
            - Since $\triangle AED$ has two known angles ($\angle EAD = 45^\circ$ from the perpendicular intersection, and another angle that's part of the original triangle), we can find its third.
            - Knowing this information allows us to calculate other relevant angles in the problem.

        **Summary:** The goal is to determine $\angle ADB$, which involves understanding relationships within an isosceles triangle where medians intersect perpendicularly with angle bisectors, indicating right-angled triangles and equal side lengths due to symmetry.
</thought>

<solution>
    Goal: Find the measure of angle $ADB$ in the given isosceles triangle.

1. **Translate**: Recognize that $\triangle ADE$ forms a 45-degree angle at point E because CE intersects AD perpendicularly, making it part of an equilateral triangle.
2. **Apply**: Since we know two angles ($\angle EAD = 90^\circ$, and another is $45^\circ$), the third can be found using basic trigonometry principles or recognizing that $\triangle AED$ must have a total angle sum equal to $180^\circ$. This implies one of its other angles, not directly given but part of our triangle's structure due to symmetry.
3. **Relabel**: Knowing this information allows us to infer the measure of $\angle EAD$, which is crucial for determining $\triangle ADB$'s properties.

Thus, considering that $AB = BC$ and knowing relationships within an equilateral triangle formed by intersecting medians with angle bisectors in a right-angled configuration, we can conclude:

The final answer is: \boxed{45}

In [27]:
print(rft_base_eval_data['parsed_answer'][0])

**Goal:** Find the equation of the curve obtained after rotating \( y = f(x) \) counterclockwise by 90 degrees around (1,-1).

    - Translate all points so that point (1,-1) becomes the origin: This involves shifting both x and y coordinates.
        * New X-coordinate for any given point is its original X minus one, because we're moving left.
        * New Y-coordinate for any given point is its original Y plus 2, as we move up by two units to counteract being shifted down initially.

    - Rotate the translated graph counterclockwise: This involves swapping x and y coordinates but also changing their signs due to rotation direction.

    - Relabel so that (1,-1) becomes the origin again. Since our translation already moved it there, we just need to reverse those steps in terms of coordinate changes.

Thus, the transformed equation is \(y = f^{-1}(-x + 2)\), making the correct answer \boxed{C}.

RAGAS Evaluation:

In [28]:
#Next 2 lines are required if running the code in Lightning AI Notebook:
import nest_asyncio
nest_asyncio.apply()

def get_rag_evaluation(embed_name, dataset, model_name):
    
    
    ragas_data = []
    for _, row in dataset.iterrows():
        
        obj ={
            'question' : row['question'],
            'contexts' : [row['contexts']],
            'ground_truth' : row['ground_truth'],
            'answer' : row['parsed_answer']
            
        }
        ragas_data.append(obj)
    
    data = Dataset.from_list(ragas_data)

    # 1. Setup an OpenAI-compatible client for Ollama
    # Ollama provides an OpenAI-compatible endpoint at /v1 --> If any other model to be used here:
    client = OpenAI()

    # 2. Use the llm_factory instead of LangchainLLMWrapper
    # Use provider="openai" to use the compatible client
    #LLM given here is the judge. So, use the same LLM that is used to generate this synthetic data
    evaluator_llm = llm_factory(model_name, client=client, max_tokens = 4096)

    #Throwing some errors so switched to LangchainEmbeddingsWrapper:
    # evaluator_embeddings = embedding_factory("openai", model=embed_name, client=client)

    # lc_embeddings = OllamaEmbeddings(
    # model=embed_name  # e.g. "nomic-embed-text"
    # )

    lc_embeddings = OpenAIEmbeddings(model=embed_name)
    ragas_embeddings = LangchainEmbeddingsWrapper(lc_embeddings)
    
    #Defining the metrics
    m1 = Faithfulness(llm=evaluator_llm)
    m2 = AnswerRelevancy(llm=evaluator_llm, embeddings=ragas_embeddings)
    m3 = AnswerCorrectness(llm=evaluator_llm, embeddings=ragas_embeddings)
    m4 = ContextPrecision(llm=evaluator_llm)

    metric_list = [m1, m2, m3, m4]
    
    results = evaluate(dataset=data,
                       metrics=metric_list,
                       embeddings=ragas_embeddings,
                        )
    eval_df = results.to_pandas()
    return eval_df

In [29]:
eval_df = get_rag_evaluation(embed_name="text-embedding-ada-002", dataset=rft_base_eval_data, 
                             model_name="gpt-4o") #Using the same model that we used earlier to generate the synthetic data

/tmp/ipykernel_3710/796424102.py:38: LangChainDeprecationWarning: The class `OpenAIEmbeddings` was deprecated in LangChain 0.0.9 and will be removed in 1.0. An updated version of the class exists in the `langchain-openai package and should be used instead. To use it run `pip install -U `langchain-openai` and import as `from `langchain_openai import OpenAIEmbeddings``.
  lc_embeddings = OpenAIEmbeddings(model=embed_name)
/tmp/ipykernel_3710/796424102.py:39: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  ragas_embeddings = LangchainEmbeddingsWrapper(lc_embeddings)

Evaluating:   0%|          | 0/200 [00:00<?, ?it/s]

[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
[ragas.prompt.pydantic_prompt|WARNING]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.

In [30]:
eval_df.head()

,user_input,retrieved_contexts,response,reference,faithfulness,answer_relevancy,answer_correctness,context_precision
0,Return your final response within \boxed{}. Gi...,[['**Solution:**\nTo determine the equation of...,**Goal:** Find the equation of the curve obtai...,**Solution:**\nTo determine the equation of th...,0.600000,0.897359,0.485601,1.0
1,Return your final response within \boxed{}. Pr...,[['**Solution:**\n\nTo prove the inequality:\n...,Goal: Prove the inequality involving real numb...,**Solution:**\n\nTo prove the inequality:\n\[\...,0.384615,0.872488,0.415772,1.0
2,Return your final response within \boxed{}. If...,[['**Solution:**\nGiven the equation \\(\\log_...,<thought>\n **Analysis:** The problem invol...,**Solution:**\nGiven the equation \(\log_2 x^2...,0.700000,0.825505,0.556575,1.0
3,Return your final response within \boxed{}. A ...,[['**Solution:**\n1. The original ratio of but...,Goal: Find the required amount of butter for a...,**Solution:**\n1. The original ratio of butter...,0.500000,0.847123,0.529297,1.0
4,Return your final response within \boxed{}. Gi...,[['**Solution:**\n\n1. **Separate the integer ...,The goal is to rewrite the fraction \( \frac{1...,**Solution:**\n\n1. **Separate the integer par...,0.250000,0.824212,0.363233,1.0

Baseline scores:

In [31]:
print("Initial Scores before Fine-Tuning...!")
mean_faithfulness_score = eval_df['faithfulness'].mean()
mean_answer_relevancy_score = eval_df['answer_relevancy'].mean()
mean_answer_correctness_score = eval_df['answer_correctness'].mean()
print("Mean Faithfulness Score : ", mean_faithfulness_score)
print("Mean Answer Relevancy Score :", mean_answer_relevancy_score)
print("Mean Answer Correctness Score :", mean_answer_correctness_score)

Initial Scores before Fine-Tuning...!
Mean Faithfulness Score :  0.46980452967602815
Mean Answer Relevancy Score : 0.8347674458794093
Mean Answer Correctness Score : 0.500974452132806

In [32]:
eval_df.to_csv('../data/rft_baseModel_evaluationScores.csv', index=False)